#######################################################################################
# Book settings
title: Differential privacy # The title of the book. Will be placed in the left navbar.
author: Lucas Rosenblatt, Bernease ???, Andrii Stadnik, Anastasia Holovenko, Taras Rumerzhak # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
# logo                        : ""  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
# exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

#######################################################################################
# Execution settings
execute:
  timeout: 100
  execute_notebooks         : force  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : false
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button

repository:
  url                       : https://github.com/DataResponsibly/SynRD  # The URL to your book's repository
  # path_to_book              : "book"  # A path to your book's folder, relative to the repository root.
  # branch                    : main  # Which branch of the repository should be used when creating links

launch_buttons:
  colab_url: "https://colab.research.google.com"

# https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
