[package]
name = "explore_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
anyhow = "1.0.58"
indicatif = "0.16.2"
itertools = "0.10.3"
